<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_menu</name>
   <tag></tag>
   <elementGuidId>6604d1d8-11b1-44d9-ab48-2de06965dba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>69372c6c-31cb-4c34-af0c-0e6f3fe1fce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgMenu</value>
      <webElementGuid>0cb90307-6630-419a-a7fb-1c134d45967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/menu.png</value>
      <webElementGuid>6df1be4c-dd1f-438a-9f66-c2f95e1dd455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div/a[1]/div/img</value>
      <webElementGuid>2944bc1e-827b-4c0f-bc68-f0eb01e46aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgMenu']</value>
      <webElementGuid>77c50e35-9051-48c3-8664-56726bbe3e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuPadding']/img</value>
      <webElementGuid>0a9c21f2-89c7-4abd-9719-c3d54d6bf8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7c5e3eb5-98c8-497d-b11e-004db98adc7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgMenu' and @src = 'Images/menu.png']</value>
      <webElementGuid>df616d10-637b-48b1-acab-6d42dd8c3c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
