<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_escalate_process</name>
   <tag></tag>
   <elementGuidId>cffdd5b1-78c5-4908-b903-c3d4f194d93a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTask_ibProcess_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTask_ibProcess_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cfbe4de-4a6e-440b-9878-75067cda3dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>91007ab5-86e9-4805-8b62-1596ddbbe85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTask$ctl02$ibProcess</value>
      <webElementGuid>5fa2bb38-5884-45e2-bd1a-003b31a656e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTask_ibProcess_0</value>
      <webElementGuid>523ddde7-0942-40eb-99c4-810d18bfbae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/apvProcessIcon.png</value>
      <webElementGuid>a9114901-0f9f-4016-a059-84a9c7df47f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvTask$ctl02$ibProcess&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>521b86bb-ebdd-4e49-8a1a-404ab0bc176d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[2]/div/div[2]/table/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>4da43a10-bd16-451d-9e21-b95f0f754c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Escalate Bucket/Escalate Bucket DERO to FRO Approval/iframe_Welcome, ARIF BUDIARTO, National Des_9f4bf7</value>
      <webElementGuid>a64cc574-d49b-4cca-9cbe-3f4ef0d29d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTask_ibProcess_0']</value>
      <webElementGuid>cf64c160-0fa7-4828-9adc-99945591c675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTask']/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>97452607-3610-450c-9f55-e698cfdca403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>92b26300-11b1-4997-b334-1a0f93406509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvTask$ctl02$ibProcess' and @id = 'gvTask_ibProcess_0' and @src = '../../Images/apvProcessIcon.png']</value>
      <webElementGuid>25d97aa1-eae4-40d7-9987-ef3f277bdee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
