<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MADE IN_rptAttributectl00txtAttrContent</name>
   <tag></tag>
   <elementGuidId>22fa82a6-06a1-410f-9869-7486648e6bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rptAttribute_txtAttrContent_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rptAttribute_txtAttrContent_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[6]/div/div[8]/div/table[1]/tbody/tr/td[2]/input[count(. | //*[@ref_element = 'Object Repository/New Applicatoin/Application Asset Data - NEW/iframe_Term  Condition_appForm']) = count(//*[@ref_element = 'Object Repository/New Applicatoin/Application Asset Data - NEW/iframe_Term  Condition_appForm'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rptAttribute$ctl00$txtAttrContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptAttribute_txtAttrContent_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[6]/div/div[8]/div/table[1]/tbody/tr/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DEPRECATED - New Applicatoin/Application Asset Data - NEW/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rptAttribute_txtAttrContent_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAssAttr']/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
