<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select (1)</name>
   <tag></tag>
   <elementGuidId>b6781114-e16c-4e40-af98-bac7b2461074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','INVESTASI NON PAKET','ucLookupProdOffer_uclProductOffering_hd2','40610','ucLookupProdOffer_uclProductOffering_hd3','NONPAKETINVESTASI');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Application (NEW)/Irregular - Upload Installment/iframe_Welcome, TITO ARI PRABOWO, TANGERANG_7a5bd7</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NONPAKETINVESTASI'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVESTASI NON PAKET'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','INVESTASI NON PAKET','ucLookupProdOffer_uclProductOffering_hd2','40610','ucLookupProdOffer_uclProductOffering_hd3','NONPAKETINVESTASI');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:ProductOfferingLookup(&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;INVESTASI NON PAKET&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;40610&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;NONPAKETINVESTASI&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
   </webElementXpaths>
</WebElementEntity>
