<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_select_zipCode1</name>
   <tag></tag>
   <elementGuidId>c88af9bd-7a69-4e09-9a33-f723bcf330b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucAddrNpwp_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucAddrNpwp_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddrNpwp_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ZipCode('ucAddrNpwp_ucLookupZipCode_uclZipCode_txt','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd1','12780','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd2','PANCORAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd3','PANCORAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd4','JAKARTA SELATAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd5','-','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd6','Wil. Kota Jakarta Selatan','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd7','161');;overlay('mdnucAddrNpwp_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddrNpwp_ucLookupZipCode_uclZipCode', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div/div[4]/div/div/table/tbody/tr[3]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[7]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EKYC/Master/Supplier Branch Member/Supplier/iframe_Welcome, usersatu, HEAD OFFICE, Supe_749e6f</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucAddrNpwp_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucAddrNpwp_ucLookupZipCode_uclZipCode_umd_ctl00_gvL']/tbody/tr[2]/td[7]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wil. Kota Jakarta Selatan'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANCORAN MAS'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANCORAN MAS'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ZipCode('ucAddrNpwp_ucLookupZipCode_uclZipCode_txt','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd1','12780','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd2','PANCORAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd3','PANCORAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd4','JAKARTA SELATAN','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd5','-','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd6','Wil. Kota Jakarta Selatan','ucAddrNpwp_ucLookupZipCode_uclZipCode_hd7','161');;overlay('mdnucAddrNpwp_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddrNpwp_ucLookupZipCode_uclZipCode', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
   </webElementXpaths>
</WebElementEntity>
