<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_menu_agrmnt_appr_ttd</name>
   <tag></tag>
   <elementGuidId>6031efd7-d64f-4dc3-96b7-f85f548f0071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#12_C_uc12_rptApproval_lbApproval1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='12_C_uc12_rptApproval_lbApproval1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1141ca9-d6a3-4e47-b6f9-72625d7cc01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12_C_uc12_rptApproval_lbApproval1</value>
      <webElementGuid>3ea56bf6-ead0-47a8-953f-de083359e41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkToDo</value>
      <webElementGuid>1cc30e89-c234-4728-984e-da70093ce49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;12$C$uc12$rptApproval$lbApproval1&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../RefCommon/Approval/AgrmntRelatedApprovalTasks.aspx?ApvCategory=AGRMNT_TRF&amp;ApvTitle=Agreement Transfer Approval&quot;, false, true))</value>
      <webElementGuid>c8b39ba4-b758-418e-9ac9-53faad99f22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agreement Transfer Approval</value>
      <webElementGuid>446072f1-ae2c-4267-b6f1-411ff2592dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[3]/div[1]/table/tbody/tr[2]/td[2]/div/div/a[3]</value>
      <webElementGuid>aff022e0-de01-4c15-b422-c4c1d7f4f5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf approval/iframe_Welcome, SUGIHARTINI, TANGERANG, Ser_66dd95</value>
      <webElementGuid>90b6fdf8-8889-4903-9395-96ad1c591fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='12_C_uc12_rptApproval_lbApproval1']</value>
      <webElementGuid>f392a65a-e117-48e0-885b-415be106feeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12_C_uc12_upThingsToDo']/a[3]</value>
      <webElementGuid>5200380f-96f8-42db-b081-31b8b8eeecfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agreement Transfer Approval')]</value>
      <webElementGuid>2dd42033-b6ac-4d7c-be25-60923e417093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/following::a[1]</value>
      <webElementGuid>e1e31f9a-fc8d-4626-82cf-08eb2c53c10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Document Release Approval Task'])[1]/following::a[2]</value>
      <webElementGuid>0815c12a-0f5d-4e29-88cc-a057d4181623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[1]/preceding::a[1]</value>
      <webElementGuid>010dde71-1153-46a5-85e2-750b4f993cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Checklist'])[1]/preceding::a[2]</value>
      <webElementGuid>bca74866-a47d-4bd6-b71b-44973965e829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agreement Transfer Approval']/parent::*</value>
      <webElementGuid>34646a8a-0866-41f1-b46a-ed5940ffa6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;12$C$uc12$rptApproval$lbApproval1&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../RefCommon/Approval/AgrmntRelatedApprovalTasks.aspx?ApvCategory=AGRMNT_TRF&amp;ApvTitle=Agreement Transfer Approval&quot;, false, true))')]</value>
      <webElementGuid>e6899636-cbaf-411d-bbd0-6052278bf5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>c92a016a-c283-42f1-8603-46c9c44758c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '12_C_uc12_rptApproval_lbApproval1' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;12$C$uc12$rptApproval$lbApproval1&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../RefCommon/Approval/AgrmntRelatedApprovalTasks.aspx?ApvCategory=AGRMNT_TRF&amp;ApvTitle=Agreement Transfer Approval&quot;, false, true))' and (text() = 'Agreement Transfer Approval' or . = 'Agreement Transfer Approval')]</value>
      <webElementGuid>3032b6c7-55ac-4e73-9d36-b27de0cddfe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
