<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_menu_asset_inv_approval</name>
   <tag></tag>
   <elementGuidId>ecb5bc6b-7387-4f39-8e7f-739133cdfb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#12_C_uc12_rptApproval_lbApproval0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='12_C_uc12_rptApproval_lbApproval0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Collection Asset Inventory Approval' or . = 'Collection Asset Inventory Approval') and @ref_element = 'Object Repository/COLLECTION/Asset Inventory/Asset Inventory Approval/iframe_Welcome, IMAN SATRIA SIDABUTAR, Jaka_ccde7f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b50a534-a861-4bc5-a7b4-aecbb5dff598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12_C_uc12_rptApproval_lbApproval0</value>
      <webElementGuid>3f9a2ca9-43cc-420a-865f-361b089f0901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkToDo</value>
      <webElementGuid>124d0386-1d94-472d-a775-8571af1c2087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;12$C$uc12$rptApproval$lbApproval0&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../RefCommon/Approval/AgrmntRelatedApprovalTasks.aspx?ApvCategory=COLL_ASSET_INV_REQ&amp;ApvTitle=Collection Asset Inventory Approval&quot;, false, true))</value>
      <webElementGuid>f0413e92-8fbf-4bd7-9052-e444dfc863c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collection Asset Inventory Approval</value>
      <webElementGuid>dbbacf12-21b5-4c4d-9c55-2bb2fd7c816f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[3]/div[1]/table/tbody/tr[2]/td[2]/div/div/a[1]</value>
      <webElementGuid>46ce42d7-4025-4ff2-bfd7-cb5a77bc430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Asset Inventory/Asset Inventory Approval/iframe_Welcome, IMAN SATRIA SIDABUTAR, Jaka_ccde7f</value>
      <webElementGuid>d53e55f9-67ff-4c2f-86dc-ae2d19ce262c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='12_C_uc12_rptApproval_lbApproval0']</value>
      <webElementGuid>1bc8b30b-1801-4894-8ea2-2487e632cecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='12_C_uc12_upThingsToDo']/a</value>
      <webElementGuid>513b8de8-9d54-44d6-a14c-04d462daf80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Collection Asset Inventory Approval')]</value>
      <webElementGuid>d3a9abbe-b4a0-45ac-a3cd-a4400aa0dc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Things To Do'])[1]/following::a[2]</value>
      <webElementGuid>27d058ce-3378-40d2-8369-73684ca0bb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/following::a[2]</value>
      <webElementGuid>45a32df1-9b08-4ba4-b6a0-ca3207c3f8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/preceding::a[1]</value>
      <webElementGuid>23602d63-8032-4259-9197-e6f0d6a30d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collection Return From Disbursement'])[1]/preceding::a[2]</value>
      <webElementGuid>a9d08349-f319-4f70-9b59-33fb6723a025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collection Asset Inventory Approval']/parent::*</value>
      <webElementGuid>0d738612-8822-4c23-aca7-a445f65119f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;12$C$uc12$rptApproval$lbApproval0&quot;, &quot;&quot;, false, &quot;&quot;, &quot;../RefCommon/Approval/AgrmntRelatedApprovalTasks.aspx?ApvCategory=COLL_ASSET_INV_REQ&amp;ApvTitle=Collection Asset Inventory Approval&quot;, false, true))')]</value>
      <webElementGuid>d9192a61-07d8-4045-9617-9e9a5a08be7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/a</value>
      <webElementGuid>fd7ecf09-5fa0-412b-ba2d-61523340e600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
