<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cancel2</name>
   <tag></tag>
   <elementGuidId>35274be5-10b1-4f53-ad37-d88a226b6b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssignmentPaging_imbCancel_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssignmentPaging_imbCancel_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div/div[4]/div/table/tbody/tr[3]/td[11]/input[count(. | //*[@ref_element = 'Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[@ref_element = 'Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssignmentPaging$ctl03$imbCancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssignmentPaging_imbCancel_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/cancel.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure you want to cancel this task?');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div/div[4]/div/table/tbody/tr[3]/td[11]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssignmentPaging_imbCancel_1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssignmentPaging']/tbody/tr[3]/td[11]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[11]/input</value>
   </webElementXpaths>
</WebElementEntity>
