<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_transaction_ref_no</name>
   <tag></tag>
   <elementGuidId>65948f7f-3715-41bd-8512-0fb39eff8b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[1]/div/div[2]/div[1]/table/tbody/tr[3]/td[2]/input[count(. | //*[@name = 'ucSearch$txtTrxRefNo_ltlSrvyTaskRefNoSch' and @type = 'text' and @id = 'ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch' and @ref_element = 'Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[@name = 'ucSearch$txtTrxRefNo_ltlSrvyTaskRefNoSch' and @type = 'text' and @id = 'ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch' and @ref_element = 'Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtTrxRefNo_ltlSrvyTaskRefNoSch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[1]/div/div[2]/div[1]/table/tbody/tr[3]/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New Application (NEW)/Survey Assignment/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNoSch']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr[3]/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
