<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_txt_CustEmergencyContact_Name</name>
   <tag></tag>
   <elementGuidId>82879bd1-4464-460d-a81d-b2432bda0483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_CustEmergencyContact_Name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[3]/div/div[3]/table/tbody/tr[1]/td[2]/input[count(. | //*[@ref_element = 'Object Repository/Corporate Customer/Contact Information/iframe_Other Attribute_custForm']) = count(//*[@ref_element = 'Object Repository/Corporate Customer/Contact Information/iframe_Other Attribute_custForm'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_CustEmergencyContact_Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_CustEmergencyContact_Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_CustEmergencyContact_Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div/div[3]/table/tbody/tr[1]/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Corporate Customer/Contact Information/iframe_Other Attribute_custForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_CustEmergencyContact_Name']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dEmergencyContactData']/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
