<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, SUGIHARTINI, TANGERANG, Ser_66dd95</name>
   <tag></tag>
   <elementGuidId>12bc3b79-3c54-452c-b700-21e079632e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8dbcebef-a014-4873-8bb4-0b408cdee5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>be6e9647-e751-44be-9525-f03af107f3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>36bb4ebb-391c-42c4-9d70-fce84f3c4220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aba8fba9-59a1-4b97-bc25-b1b6614f93d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Amendment/AmendmentMainPage.aspx</value>
      <webElementGuid>9fde8e4b-bb37-4d5d-8ad3-237a40602fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPage&quot;)</value>
      <webElementGuid>a7873faf-01bc-4f9c-9a54-c37a150aa2e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainPage']</value>
      <webElementGuid>ecaf19c4-33d2-4934-b520-a34cb52a855e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[3]</value>
      <webElementGuid>c61b8ad0-7782-4fa3-a96f-fa4faa8de4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>1db9a455-d9c3-44ed-bafa-21a9ab1374f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainPage' and @name = 'mainPage' and @src = 'Amendment/AmendmentMainPage.aspx']</value>
      <webElementGuid>28184410-95ed-4a78-a54b-2eda0c245245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
