<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agree_no</name>
   <tag></tag>
   <elementGuidId>3424039d-a6a1-4151-8915-f54e264901c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvPaging_lblAgrmntNo_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gvPaging_lblAgrmntNo_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e773ab1-d43d-46a7-be1c-61a388706600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvPaging_lblAgrmntNo_0</value>
      <webElementGuid>bc4fe38b-467b-46b1-918e-c222f4a38902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvPaging$ctl02$lblAgrmntNo&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>688e8560-e118-4d5d-96ba-55df0d910c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2100009415</value>
      <webElementGuid>b7a474e4-3b74-4cab-ad04-b31d04f24e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div[3]/div[2]/div/div/div[2]/table/tbody/tr[2]/td[1]/a</value>
      <webElementGuid>b8003896-1413-49d5-99e8-e754b03f7f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Escalate Bucket/Escalate Bucket Inquiry/iframe_Welcome, TYAS UNTORO, Jakarta Centra_b10c37</value>
      <webElementGuid>950424e2-f103-4f65-b7ee-12adf8383631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gvPaging_lblAgrmntNo_0']</value>
      <webElementGuid>3f6ee914-9d03-45ca-bf95-ae66e6a83e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvPaging']/tbody/tr[2]/td/a</value>
      <webElementGuid>5da13892-6c6c-4fde-8684-0943f67c8e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2100009415')]</value>
      <webElementGuid>dba1634b-5f48-4ace-8d7c-40857372fcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSACTION STATUS'])[1]/following::a[1]</value>
      <webElementGuid>a6147284-2656-47cd-88f8-8868a37da2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXECUTE DATE'])[1]/following::a[2]</value>
      <webElementGuid>a4169262-a9e6-455f-8c02-426d8df1f6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDEH'])[1]/preceding::a[1]</value>
      <webElementGuid>87589ed6-0f9c-4097-b292-771f016ec2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execute'])[2]/preceding::a[3]</value>
      <webElementGuid>57d8ed25-2704-4157-ab40-5ad8ea40b9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2100009415']/parent::*</value>
      <webElementGuid>cb957127-6750-4b64-96ab-0439ba00515a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvPaging$ctl02$lblAgrmntNo&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>7425b07b-721f-4e94-b20e-085d5e75585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>87bb8c4c-7852-4fd2-8718-435ed94d3e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gvPaging_lblAgrmntNo_0' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvPaging$ctl02$lblAgrmntNo&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = '2100009415' or . = '2100009415')]</value>
      <webElementGuid>cefcb81d-9d7c-47ad-8364-f7683ed29e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
