<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Copyright  AdIns 2011. All Right Rese_9109c2</name>
   <tag></tag>
   <elementGuidId>9c02aa39-0f68-4307-8c83-fac52afc3185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60718343-e958-4341-ac36-5cc32c17fdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>44718db6-6cdd-4347-939d-cfcc82060ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>42ab7553-a855-49ff-8be1-8f096bc2a3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>189d88ee-b411-4bfe-9a22-dab7337e2811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(!basicLoginValidation()) return false;</value>
      <webElementGuid>90c7b885-de55-47e5-87ee-26e2a3f08a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>588dbc41-081a-4e9f-ac80-1fddb37351b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbLogin&quot;)</value>
      <webElementGuid>5e37a034-1b70-4183-99d4-471f062c0e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbLogin']</value>
      <webElementGuid>abc56a6c-1cd1-4d2b-b9dc-911611208a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upButton']/input</value>
      <webElementGuid>70357417-d70a-4a6b-8f95-4980289db65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/input</value>
      <webElementGuid>bd018163-dda5-429d-896c-1e99dcc05dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lbLogin' and @id = 'lbLogin']</value>
      <webElementGuid>15b29bc3-acd1-4d31-ae81-9c10790c312a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
