<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_collection</name>
   <tag></tag>
   <elementGuidId>36a2bc53-f318-4253-ba17-087eed223c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Tab_CollHistory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Tab_CollHistory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>391b2dde-2a3c-488b-ba51-2eb148226107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Tab_CollHistory</value>
      <webElementGuid>282f8454-4ee5-4851-8a70-cb1f19cad083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabDisabled</value>
      <webElementGuid>df48b216-4bcb-495b-ba69-6196914d5a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('lb_Tab_CollHistory','')</value>
      <webElementGuid>32434543-0ccc-4d42-a6ea-68cb4bb12ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLLECTION</value>
      <webElementGuid>0debe22c-ca63-42bc-93eb-69c35991cd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[5]/div/a[8]</value>
      <webElementGuid>3dc60411-d421-4815-8675-afe615329c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Tab_CollHistory']</value>
      <webElementGuid>c52ff702-001a-4315-97b6-bcc1d6710a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dTab']/a[8]</value>
      <webElementGuid>db5e40ab-9cf6-4aae-a284-b961fd07ad6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'COLLECTION')]</value>
      <webElementGuid>be616ec2-7228-4a8c-b2f2-506dc5e03783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOCUMENT'])[1]/following::a[1]</value>
      <webElementGuid>f2a1b1aa-7e1b-4dd4-b0d3-36702cc6ec30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMMARY'])[1]/following::a[2]</value>
      <webElementGuid>18941387-056e-44ea-961b-a5068c5aeacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMEDIAL'])[1]/preceding::a[1]</value>
      <webElementGuid>5ac157aa-ea86-4449-8340-1e3f93aecb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT HISTORY'])[1]/preceding::a[2]</value>
      <webElementGuid>c5bb8ebd-875d-4edf-990b-95e0ded5f4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COLLECTION']/parent::*</value>
      <webElementGuid>3c8f71b0-8af5-4bf3-9767-22293a8e80c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('lb_Tab_CollHistory','')&quot;)]</value>
      <webElementGuid>80d1ec5d-47e4-40ae-92a7-e4cd58f3a77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]</value>
      <webElementGuid>6ac1c683-4393-4127-8df3-9b8ff1d5fa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Tab_CollHistory' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;lb_Tab_CollHistory&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'COLLECTION' or . = 'COLLECTION')]</value>
      <webElementGuid>c7f295be-9d63-41ed-8e74-10646cdfa454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
