<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select_1</name>
   <tag></tag>
   <elementGuidId>67e403d7-e3f7-4917-8460-6018689b4ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:BrandLookup('gvAsset_uclBrand_0_uclBrand_0_txt_0','gvAsset_uclBrand_0_uclBrand_0_hd1_0','TOYOTA','gvAsset_uclBrand_0_uclBrand_0_hd2_0','001','gvAsset_uclBrand_0_uclBrand_0_hd3_0','1','gvAsset_uclBrand_0_uclBrand_0_hd4_0','1');;overlay('mdngvAsset_uclBrand_0_uclBrand_0');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0_hpSelect_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FLEET/MOU/MOU Create/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_fc6acd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_gvL_0']/tbody/tr[2]/td[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:BrandLookup('gvAsset_uclBrand_0_uclBrand_0_txt_0','gvAsset_uclBrand_0_uclBrand_0_hd1_0','TOYOTA','gvAsset_uclBrand_0_uclBrand_0_hd2_0','001','gvAsset_uclBrand_0_uclBrand_0_hd3_0','1','gvAsset_uclBrand_0_uclBrand_0_hd4_0','1');;overlay('mdngvAsset_uclBrand_0_uclBrand_0');&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
