<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brand Name_gvAssetctl02uclBranduclBra_3528a7</name>
   <tag></tag>
   <elementGuidId>1954b8a4-072a-4d7b-bce9-daeaf0494501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_rptFixedSearch_0_txtSearchValue_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_rptFixedSearch_0_txtSearchValue_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAsset$ctl02$uclBrand$uclBrand$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_rptFixedSearch_0_txtSearchValue_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_rptFixedSearch_0_txtSearchValue_0&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FLEET/MOU/MOU Create/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_fc6acd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_rptFixedSearch_0_txtSearchValue_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gvAsset_uclBrand_0_uclBrand_0_umd_0_ctl00_0_ucS_0_upFixedSearch_0']/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/div/div/div/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
