<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Name_ucLookupTopUpAgrmntuclT_c68dd5</name>
   <tag></tag>
   <elementGuidId>07f0db51-d317-44e1-8917-f4d9604d7542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[6]/div/div[3]/div[2]/table/tbody/tr/td[2]/div/div/div/div/div[1]/div/table/tbody/tr[3]/td[2]/input[count(. | //*[@ref_element = 'Object Repository/SIAP DANA/Asset Data - Siap Dana/iframe_Term  Condition_appForm']) = count(//*[@ref_element = 'Object Repository/SIAP DANA/Asset Data - Siap Dana/iframe_Term  Condition_appForm'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupTopUpAgrmnt$uclTopUpAgr$umd$ctl00$ucS$rptFixedSearch$ctl03$txtSearchValue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[6]/div/div[3]/div[2]/table/tbody/tr/td[2]/div/div/div/div/div[1]/div/table/tbody/tr[3]/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Asset Data - Siap Dana/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr[3]/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td[2]/div/div/div/div/div/div/table/tbody/tr[3]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
