<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_select_surveyor</name>
   <tag></tag>
   <elementGuidId>f8eb2646-5ca8-496e-a765-f8c027b4fd67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSurveyor_uclSrvy_umd_ctl00_gvL_hpSelect_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupSurveyor_uclSrvy_umd_ctl00_gvL_hpSelect_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[2]/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[5]/a[count(. | //*[(text() = 'Select' or . = 'Select') and @ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[(text() = 'Select' or . = 'Select') and @ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0b2c01d-417e-4da9-9745-02e646fca3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSurveyor_uclSrvy_umd_ctl00_gvL_hpSelect_1</value>
      <webElementGuid>7f4d10ff-6777-4c1a-8f93-8a3450a9d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Surveyor('ucLookupSurveyor_uclSrvy_hd1','OARM0001','ucLookupSurveyor_uclSrvy_txt','ucLookupSurveyor_uclSrvy_hd2','ANORA RIZKI MANDIRI I','ucLookupSurveyor_uclSrvy_hd3','OARM0001','ucLookupSurveyor_uclSrvy_hd4','0','ucLookupSurveyor_uclSrvy_hd5','463');;overlay('mdnucLookupSurveyor_uclSrvy');</value>
      <webElementGuid>7efbbbcf-2205-4a7a-88e7-7de34969ecfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>60f9b098-7021-4973-b5d6-f0cfd4730e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[2]/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>413cd91e-020b-48ed-815d-7fe50b900cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
      <webElementGuid>5aaa3cfa-bc97-4f96-be17-dcddb71b7b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupSurveyor_uclSrvy_umd_ctl00_gvL_hpSelect_1']</value>
      <webElementGuid>e67949d7-f94c-4c83-9ecb-d89ab280b120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupSurveyor_uclSrvy_umd_ctl00_gvL']/tbody/tr[3]/td[5]/a</value>
      <webElementGuid>d03c93e5-8162-4fb7-8bfd-40eaf89ba506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
      <webElementGuid>82dd5a8c-fadc-4683-a51c-de1c7f5a4374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OARM0001'])[2]/following::a[1]</value>
      <webElementGuid>ee4f91e8-ee3b-439f-9a88-3a020510813f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANORA RIZKI MANDIRI I'])[1]/following::a[1]</value>
      <webElementGuid>148c2fd4-8dbd-4b14-a688-6d2ad02a2439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OARM0002'])[1]/preceding::a[1]</value>
      <webElementGuid>99d07694-05f8-4720-83c0-ba5bbfdbe8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANORA RIZKI MANDIRI II'])[1]/preceding::a[1]</value>
      <webElementGuid>a6dc9912-0150-40a2-9d6b-254d2e555da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:Surveyor('ucLookupSurveyor_uclSrvy_hd1','OARM0001','ucLookupSurveyor_uclSrvy_txt','ucLookupSurveyor_uclSrvy_hd2','ANORA RIZKI MANDIRI I','ucLookupSurveyor_uclSrvy_hd3','OARM0001','ucLookupSurveyor_uclSrvy_hd4','0','ucLookupSurveyor_uclSrvy_hd5','463');;overlay('mdnucLookupSurveyor_uclSrvy');&quot;)]</value>
      <webElementGuid>7052f510-c287-4968-9f8c-2461c847fc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/a</value>
      <webElementGuid>2f94f6c2-ba6b-46a9-b228-ee3d9015f4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupSurveyor_uclSrvy_umd_ctl00_gvL_hpSelect_1' and @href = concat(&quot;javascript:Surveyor(&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;OARM0001&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ANORA RIZKI MANDIRI I&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;OARM0001&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupSurveyor_uclSrvy_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;463&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupSurveyor_uclSrvy&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6fff7e23-55e0-45a3-bc5c-d6ab5a3fe384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
