<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_reassign1</name>
   <tag></tag>
   <elementGuidId>c9b2e747-13fd-45ff-a665-6da324f06a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvSurvey_imbReAssign_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvSurvey_imbReAssign_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[2]/div/div[2]/div[2]/table/tbody/tr[2]/td[15]/input[count(. | //*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2161a222-d7bf-42c8-af1a-6bc1b1adc139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>7e163ea3-de37-460c-8bf0-fa5dc8e244c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvSurvey$ctl02$imbReAssign</value>
      <webElementGuid>42b6ee08-f9fd-40e4-93ac-9cc2e96dba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvSurvey_imbReAssign_0</value>
      <webElementGuid>24003873-b2c7-47ef-9a21-0b8af2a3268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Review</value>
      <webElementGuid>dedc61f2-4655-41ad-b930-ef695ee0781d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Edit.gif</value>
      <webElementGuid>837bcaaa-f4de-4e8a-a276-f510a8920b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[2]/div/div[2]/div[2]/table/tbody/tr[2]/td[15]/input</value>
      <webElementGuid>8ebb910c-b532-4518-a7a6-7ef7975f0534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
      <webElementGuid>9be63d46-6b18-4a47-8137-1d03140484fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvSurvey_imbReAssign_0']</value>
      <webElementGuid>d2a95d26-738d-4384-87b4-93d5c2912b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvSurvey']/tbody/tr[2]/td[15]/input</value>
      <webElementGuid>cbae84e5-8e45-4bfb-b971-d3734132b79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/input</value>
      <webElementGuid>967c58c0-f3d6-4fa2-887c-2e4355fb10ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvSurvey$ctl02$imbReAssign' and @id = 'gvSurvey_imbReAssign_0' and @title = 'Review' and @src = '../../Images/Edit.gif']</value>
      <webElementGuid>08983b6a-5450-4b80-94bb-9790c4d53acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
