<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_trx_ref_no</name>
   <tag></tag>
   <elementGuidId>5854e28a-0f3b-4aac-886f-f927141679cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[1]/div/div[2]/div[1]/table/tbody/tr[3]/td[2]/input[count(. | //*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae965ac8-758b-486c-bcd9-df9005492154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtTrxRefNo_ltlSrvyTaskRefNo</value>
      <webElementGuid>2efcfd02-f373-41a2-970b-c8726346c4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acfbd06e-b359-45e8-b6b0-b8d3fee16d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo</value>
      <webElementGuid>a3bc2544-5799-4f21-9a8b-1a7bd5d0557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>6f589b00-6510-460b-94ac-f95851b2288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[1]/div/div[2]/div[1]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>da2e39fb-8d6b-4d1b-9dd2-668e9dc07f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
      <webElementGuid>5502271c-1bb0-436d-a8b2-da8bd1a88d36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      <webElementGuid>34ce5a0a-1b21-4a7f-b78f-b352759c3bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>13be5538-8d7a-43a4-ba1d-d321a6fcc363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>13d6525f-1b23-444d-834a-0f7ff11b0f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtTrxRefNo_ltlSrvyTaskRefNo' and @type = 'text' and @id = 'ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      <webElementGuid>8ee58a79-e6af-4f24-8777-217e7a12baf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
