<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_search_surveyor_name</name>
   <tag></tag>
   <elementGuidId>7a1b2863-d302-4021-a12f-77e087bd10c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupSurveyor_uclSrvy_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucLookupSurveyor_uclSrvy_imb']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[2]/div[2]/table/tbody/tr[2]/td[2]/ul/li[1]/input[2][count(. | //*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158']) = count(//*[@ref_element = 'Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63fa7ec5-9a76-4d19-9c6b-46616ed51fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1385909b-5c72-4f96-8249-ff639b74750d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucLookupSurveyor$uclSrvy$imb</value>
      <webElementGuid>d62b22e3-70eb-432d-9a0c-40f917d2b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupSurveyor_uclSrvy_imb</value>
      <webElementGuid>8b865212-61a4-4756-87b6-03b1409e91f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>c846cdbc-9656-4e67-b1ac-67a786edd38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucLookupSurveyor_uclSrvy');</value>
      <webElementGuid>2508f9ae-e920-4e56-926d-dd97fa092cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[2]/div[2]/table/tbody/tr[2]/td[2]/ul/li[1]/input[2]</value>
      <webElementGuid>88f563e4-9541-4036-a086-196159d2cfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Survey Reassign/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
      <webElementGuid>eb3d3638-7a4f-484a-931c-89d8d2de8fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucLookupSurveyor_uclSrvy_imb']</value>
      <webElementGuid>2aa151be-1d1f-42f1-a770-f4d03c75f346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dPADReq']/table/tbody/tr[2]/td[2]/ul/li/input[2]</value>
      <webElementGuid>cd15d53b-f440-46da-ab65-eb1e60908dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>9663f075-3d3f-4b00-8f2a-2d1acf16a03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucLookupSurveyor$uclSrvy$imb' and @id = 'ucLookupSurveyor_uclSrvy_imb' and @src = '../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>75f89ad1-2018-44c5-9e5f-627efdf73dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
