<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asset Document_rtPlus</name>
   <tag></tag>
   <elementGuidId>0148880d-1cdb-4165-817d-9cdb318866ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rtPlus</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[4]/div[2]/div/ul/li[1]/div/span[2][count(. | //*[@ref_element = 'Object Repository/Asset Document/Borrow/Execution/iframe_Welcome, DAIRINA MANIK, JAKARTA NORT_235073']) = count(//*[@ref_element = 'Object Repository/Asset Document/Borrow/Execution/iframe_Welcome, DAIRINA MANIK, JAKARTA NORT_235073'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rtvMenuTree']/ul/li/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtPlus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[2]/div/ul/li[1]/div/span[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Asset Document/Borrow/Execution/iframe_Welcome, DAIRINA MANIK, JAKARTA NORT_235073</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rtvMenuTree']/ul/li/div/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
