<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_select_asset</name>
   <tag></tag>
   <elementGuidId>67b8d7b5-f6ed-4ab6-8877-a234f6625691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Master('ucLookupAssetMaster_uclMaster_txt','ucLookupAssetMaster_uclMaster_hd1','TOYOTA CALYA 1.2 E STD M/T','ucLookupAssetMaster_uclMaster_hd2','1.2 E STD M/T','ucLookupAssetMaster_uclMaster_hd3','4','ucLookupAssetMaster_uclMaster_hd4','1','ucLookupAssetMaster_uclMaster_hd5','3164');;overlay('mdnucLookupAssetMaster_uclMaster');__doPostBack('mdnucLookupAssetMaster_uclMaster', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div[2]/div[1]/div[3]/div[3]/table[1]/tbody/tr[2]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[2]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Credit Simulation/Company Single/iframe_Welcome, TITO ARI PRABOWO, TANGERANG_7a5bd7</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupAssetMaster_uclMaster_umd_ctl00_gvL']/tbody/tr[2]/td[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA CALYA 1.2 E STD M/T'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECT'])[3]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA CALYA 1.2 G M/T'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:Master('ucLookupAssetMaster_uclMaster_txt','ucLookupAssetMaster_uclMaster_hd1','TOYOTA CALYA 1.2 E STD M/T','ucLookupAssetMaster_uclMaster_hd2','1.2 E STD M/T','ucLookupAssetMaster_uclMaster_hd3','4','ucLookupAssetMaster_uclMaster_hd4','1','ucLookupAssetMaster_uclMaster_hd5','3164');;overlay('mdnucLookupAssetMaster_uclMaster');__doPostBack('mdnucLookupAssetMaster_uclMaster', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
