<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_menu_inquiry</name>
   <tag></tag>
   <elementGuidId>791eb768-2959-4af6-950b-3476aa8c0af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rtPlus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rtvMenuTree']/ul/li[11]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14e1537b-d645-4ea5-9b26-a94ee40a4fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtPlus</value>
      <webElementGuid>fb3f1d02-9257-4036-a34d-8bf48231d0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[2]/div/ul/li[11]/div/span[2]</value>
      <webElementGuid>5e18a33e-ec19-4d92-89a9-c37a0e320d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Inquiry Matching/iframe_Welcome, ABDUL AZIS, TANGERANG, Mark_e075b7</value>
      <webElementGuid>6632fd96-322d-482f-9197-5acc0e94d35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rtvMenuTree']/ul/li[11]/div/span[2]</value>
      <webElementGuid>85399869-c6c2-4943-9fc6-2a23767322dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>a3dc746f-41ea-4a5c-9f38-4cd4ff18f931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
