<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no_rangka_regular</name>
   <tag></tag>
   <elementGuidId>3375133f-70de-41fe-bb27-8eb95bd46f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetList_lblSerialNo2_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gvAssetList_lblSerialNo2_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>788c7e50-2441-480a-9c16-06d02d4224d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetList_lblSerialNo2_0</value>
      <webElementGuid>b2486b0c-e0ed-4b23-a0de-4310ca10c8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SDRGK5150GJ703306</value>
      <webElementGuid>65aacf6a-737c-416a-a2a9-9c8aa7f2c781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[3]/div[2]/div[2]/div[2]/table/tbody/tr[2]/td[8]/span</value>
      <webElementGuid>d584d914-6c68-4316-83a7-d6d3526b1f7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gvAssetList_lblSerialNo2_0']</value>
      <webElementGuid>a43ce1a2-d5b0-41f2-a108-f15582826f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetList']/tbody/tr[2]/td[8]/span</value>
      <webElementGuid>6213b523-bffb-4a04-81cc-e3611443548f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S15507405306'])[1]/following::span[1]</value>
      <webElementGuid>3aeb2462-1251-4c41-8710-65ed4f3b2322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARMADA AUTO TARA - TGR CIKOKOL 1'])[1]/following::span[5]</value>
      <webElementGuid>9e5f078e-80e0-4a55-b3a4-9107192fa95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zisimos Valavanis Six'])[2]/preceding::span[2]</value>
      <webElementGuid>995818a7-8338-48ee-add5-ab8e74d8a341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[1]/preceding::span[3]</value>
      <webElementGuid>6853b5d0-acb0-479d-af02-2665969d054b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SDRGK5150GJ703306']/parent::*</value>
      <webElementGuid>d3edecb1-8f17-4b94-91a6-f420b336dcb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span</value>
      <webElementGuid>3faa63c8-a959-491c-a473-b4daff1296ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gvAssetList_lblSerialNo2_0' and (text() = 'SDRGK5150GJ703306' or . = 'SDRGK5150GJ703306')]</value>
      <webElementGuid>b5d04682-16f6-4bc5-9cd6-b508ddef13ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
