<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select (2)</name>
   <tag></tag>
   <elementGuidId>ee7e113e-2c56-4a9d-8eeb-58c28d70fe96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[3]/a[count(. | //*[@ref_element = 'Object Repository/New Applicatoin/New Application - Customer/iframe_Term  Condition_appForm']) = count(//*[@ref_element = 'Object Repository/New Applicatoin/New Application - Customer/iframe_Term  Condition_appForm'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','Steve Rogersss','uclCust_uclCust_hd2','0037C20210300939','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','uclCust_uclCust_hd7','1512311','uclCust_uclCust_hd8','1512311');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div/div[2]/table/tbody/tr[2]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[3]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DEPRECATED - New Applicatoin/New Application - Customer/iframe_Welcome, ANGGO BAGUS WICAKSONO, TANG_7b644c</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan Gatot Subroto No. 123 Jakarta Selatan'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','Steve Rogersss','uclCust_uclCust_hd2','0037C20210300939','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','uclCust_uclCust_hd7','1512311','uclCust_uclCust_hd8','1512311');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
