<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, ARIF BUDIARTO, National Des_22dae8</name>
   <tag></tag>
   <elementGuidId>0c3e8c51-c627-41dd-a460-d50e8b0c8513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treeContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='treeContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d53091c1-d728-47a4-9967-2fe7ac97fc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewTree.aspx</value>
      <webElementGuid>218e9a21-6978-4cf6-8ddd-be899d8d70dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeContainer</value>
      <webElementGuid>3622dbb7-f434-4028-805c-99131fdef097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2eeaabf-7fdc-4c75-a48e-a86ce33bcd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeContainer&quot;)</value>
      <webElementGuid>5d79fdcd-2f48-4c45-ab91-a6ad36cc926c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='treeContainer']</value>
      <webElementGuid>98d5871e-149d-4277-bc43-907804cd1b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[2]</value>
      <webElementGuid>bec38784-000d-4d6f-b4ca-4a000b0da77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>dcc97e9d-44f6-4578-b143-a62c1a531c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'NewTree.aspx' and @id = 'treeContainer']</value>
      <webElementGuid>8db22125-4056-46fb-a05a-51fff813824c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
