<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ar_head_fo_role</name>
   <tag></tag>
   <elementGuidId>3e7b0413-0d91-422a-8be0-43de41d01303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uModDRole_ctl00_gvRoles_lbSelectRole_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[4]/div/div/div/table/tbody/tr[3]/td[4]/a[count(. | //*[(text() = 'Select' or . = 'Select')]) = count(//*[(text() = 'Select' or . = 'Select')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b1398f9-72e7-44f4-abad-c16ed3645bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('roleOverlay');</value>
      <webElementGuid>b3c128b3-3192-4508-8385-8d66f8c0f24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uModDRole_ctl00_gvRoles_lbSelectRole_2</value>
      <webElementGuid>9706308d-c524-43e3-96d3-359d0ec7be48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl04$lbSelectRole','')</value>
      <webElementGuid>dedccfdd-42f5-4853-ba3d-be63e6783d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>2bba0c5a-42f3-4b45-a58e-c83b520c6883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div/div/div/table/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>1050eac3-59cf-434b-a794-5a1353bcf0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_2']</value>
      <webElementGuid>86cc3ed8-a755-4ca1-9416-9a1d880c0cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uModDRole_ctl00_gvRoles']/tbody/tr[4]/td[4]/a</value>
      <webElementGuid>219f8be2-cacc-425b-a3bd-237309a69a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[3]</value>
      <webElementGuid>2607ae84-e24d-4222-8882-0985b071f225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESK COLLECTOR SUPERVISOR'])[1]/following::a[1]</value>
      <webElementGuid>5e423aa7-df07-4876-8472-f5329f1f79a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESK RELATIONSHIP SUPERVISOR'])[1]/following::a[1]</value>
      <webElementGuid>5e797e37-c243-470c-8658-b5edf7f1180f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'uModDRole_ctl00_gvRoles_lbSelectRole_2', '&quot;', ')')])[1]/preceding::a[2]</value>
      <webElementGuid>062ddc0e-7739-429e-a3f0-e6cf720dd33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl04$lbSelectRole','')&quot;)]</value>
      <webElementGuid>a3de02f0-6b81-445e-ba1a-b6e53b78d1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/a</value>
      <webElementGuid>44e1517c-2eb3-4c52-8c38-a6737fded531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uModDRole_ctl00_gvRoles_lbSelectRole_2' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;uModDRole$ctl00$gvRoles$ctl04$lbSelectRole&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>0a2cf214-0e08-43aa-9812-a7f43642c10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
