<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Survey</name>
   <tag></tag>
   <elementGuidId>5695fb5f-61c8-4a16-b9fc-d837544f6aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rModuleList_lbModuleList_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rModuleList_lbModuleList_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cb76a7f-9b21-414f-af0b-12132b94efcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rModuleList_lbModuleList_3</value>
      <webElementGuid>f6614eb8-ce4f-4942-b4a4-9d2786d66a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('rModuleList$ctl04$lbModuleList','')</value>
      <webElementGuid>59103b0a-892b-4a06-aaa4-7539cc0cdf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Survey</value>
      <webElementGuid>c4ebaaab-4abc-4345-a844-75f5ad3effb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rModuleList_lbModuleList_3&quot;)</value>
      <webElementGuid>42a5f75a-7961-4b00-9d03-28786c8ce61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Resurvey/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_c97049</value>
      <webElementGuid>14ef1b9f-38a4-4924-9f63-b147e9e45527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rModuleList_lbModuleList_3']</value>
      <webElementGuid>a2a73b42-0919-454f-801c-6a3726f87283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upModuleList']/div/div[4]/a</value>
      <webElementGuid>e4c49967-e0c3-41cf-b75c-35b872607558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Survey')]</value>
      <webElementGuid>7a860f6e-95f3-4eda-b631-4eff1fc2832a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier'])[1]/following::a[1]</value>
      <webElementGuid>f58e1ea2-5fb9-4ccf-b222-a63a8f0c7506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::a[2]</value>
      <webElementGuid>3395fbfb-de52-4299-b82f-b241281958af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Origination Reports'])[1]/preceding::a[1]</value>
      <webElementGuid>7865d4b6-558d-4b9a-a5c2-5d7b087319fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAF Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>3d904dce-c951-483e-8d3a-a40769f0bffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Survey']/parent::*</value>
      <webElementGuid>e4aaea29-c74c-42af-83fc-f423684617b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('rModuleList$ctl04$lbModuleList','')&quot;)]</value>
      <webElementGuid>27481465-4bf7-4a50-83a2-8442f6aace55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>4ad1944c-8085-44d2-96df-9fb6a6b37556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rModuleList_lbModuleList_3' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;rModuleList$ctl04$lbModuleList&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Survey' or . = 'Survey')]</value>
      <webElementGuid>897531ac-ac2c-4205-8767-09256856fe52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
