<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Transaction Reference No_ucSearchtxtTrxRefNo_ltlSrvyTaskRefNo</name>
   <tag></tag>
   <elementGuidId>d7943734-5d7c-4660-b51e-80a5e6695424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1416a336-891b-4458-b449-342d6c46a2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtTrxRefNo_ltlSrvyTaskRefNo</value>
      <webElementGuid>65320c78-ac52-47be-b9cf-7978afcd2036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20f9b1b7-e0c8-4cf6-abe6-6a7013b859c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo</value>
      <webElementGuid>b9cf4d82-3395-4fc5-b2a7-9d1f71ed00d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>e6899daa-8ed1-491a-8ed3-6019c9414eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo&quot;)</value>
      <webElementGuid>ee2efe8f-3bb9-4465-b7f8-925e0e05826b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Survey/Resurvey/iframe_Welcome, DWIYATNO, SURVEY AREA 1, BA_110158</value>
      <webElementGuid>c239aea9-07eb-4c7e-b1af-d75a14df3226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      <webElementGuid>79184a49-541a-4f3d-a907-a142687736e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>10733e21-0507-48de-81e1-918ddf6926b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>e25d75fb-5955-4770-b3ef-71d716527d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtTrxRefNo_ltlSrvyTaskRefNo' and @type = 'text' and @id = 'ucSearch_txtTrxRefNo_ltlSrvyTaskRefNo']</value>
      <webElementGuid>52e6a3b0-b11a-4179-9a1b-d2b02bcd042c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
