<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Name_uclCustuclCustumdctl00u_91e5b7</name>
   <tag></tag>
   <elementGuidId>c330f01d-cb8d-460a-8200-1b647dfe3d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[4]/div[2]/table[1]/tbody/tr[3]/td[2]/div/div/div/div/div[1]/div/table/tbody/tr[1]/td[2]/input[count(. | //*[@ref_element = 'Object Repository/FLEET/New Application - Customer/iframe_Term  Condition_appForm']) = count(//*[@ref_element = 'Object Repository/FLEET/New Application - Customer/iframe_Term  Condition_appForm'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclCust$uclCust$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[2]/table[1]/tbody/tr[3]/td[2]/div/div/div/div/div[1]/div/table/tbody/tr[1]/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FLEET/New Application - Customer/iframe_Term  Condition_appForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uclCust_uclCust_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/table/tbody/tr/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
