<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Copyright  AdIns 2011. All Right Rese_9109c2</name>
   <tag></tag>
   <elementGuidId>457369f5-59c7-402a-9ee3-5629857b5f3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edca5c15-d1e0-493a-b67e-b364174d264d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19d8bec9-0a7b-4a23-84e0-00e783d00145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>99bcfc38-6d55-4458-839e-0ddb3e53a9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>0674742d-decb-46e2-afa7-76da4f816c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(!basicLoginValidation()) return false;</value>
      <webElementGuid>7d83d787-309a-4ff4-ae09-68228c1ff959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>e2a13b6c-aa89-4f7f-957b-50510de947bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbLogin&quot;)</value>
      <webElementGuid>f3936235-af8e-4b8e-a5b6-b21695c157ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbLogin']</value>
      <webElementGuid>509556a8-3fb7-4ac1-8216-b9ad94303cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upButton']/input</value>
      <webElementGuid>9e627f9c-39ca-4dfe-955e-7b9856522635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/input</value>
      <webElementGuid>4867a655-7f91-4358-bc57-5ebb48afacda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lbLogin' and @id = 'lbLogin']</value>
      <webElementGuid>74f36d58-c294-4014-b593-82cacf2c789a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
