<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_delivery_charges</name>
   <tag></tag>
   <elementGuidId>f7470fb8-c957-46fa-9dba-488e56dc3651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[4]/div/div/div/div[2]/table/tbody/tr[7]/td[2]/input[2][count(. | //*[@ref_element = 'Object Repository/REMEDIAL/Remedial Expense v3/Remedial Expense Request v3/iframe_Welcome, TYAS UNTORO, REMEDIAL AREA _3cba35']) = count(//*[@ref_element = 'Object Repository/REMEDIAL/Remedial Expense v3/Remedial Expense Request v3/iframe_Welcome, TYAS UNTORO, REMEDIAL AREA _3cba35'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucRoSEstimation$ucINCollExpenseDeliveryCharges$txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucRoSEstimation$ucINCollExpenseDeliveryCharges$txtInput\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput','ucRoSEstimation_ucINCollExpenseDeliveryCharges_hdnInput','ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInputDummy');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[4]/div/div/div/div[2]/table/tbody/tr[7]/td[2]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/REMEDIAL/Remedial Expense v3/Remedial Expense Request v3/iframe_Welcome, TYAS UNTORO, REMEDIAL AREA _3cba35</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucRoSEstimation_ucINCollExpenseDeliveryCharges_txtInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dRoSEstimation']/table/tbody/tr[7]/td[2]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
