<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEARCH (1)</name>
   <tag></tag>
   <elementGuidId>9d1101ab-ff90-4acd-98a9-ceca0e545589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccabad64-244f-451d-a822-6a7038ab1fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>3763d9f1-f272-496f-8207-288dfc8e764a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>891a015c-5d59-47c9-8408-17663e34ee6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>18cc630c-d99e-47ad-ae70-7d278ad437d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>61ead725-f9a9-4f1f-98b2-83d7c86519d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>803d77c6-8844-464b-924d-7c375e9ecf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get App No/iframe_Term  Condition_appForm</value>
      <webElementGuid>6a7d4fde-f911-42e5-ab90-b033a2049e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>c32b16f9-5cc3-428d-9774-6b138844696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uclCust_uclCust_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>f40b4831-f9c2-41da-b9a2-9f52786e7be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH')]</value>
      <webElementGuid>c69a5e5c-6d5b-422f-a0f2-70f99ab14fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::a[1]</value>
      <webElementGuid>07d915bc-e951-4d7a-85c0-69d6a47feaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/following::a[1]</value>
      <webElementGuid>aadaaed5-9466-4823-a417-1fdb226b6650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/preceding::a[1]</value>
      <webElementGuid>1cdc6f28-1895-4e6c-9bf1-2d272b1b4a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[2]</value>
      <webElementGuid>1bacc54e-2a24-4811-a5e6-cc88d42eb85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>6a43b1d4-fb60-45e5-b36f-91deea160dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>62ad0294-dc3a-434d-bc68-ac655d9e4cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>0aa8417e-c5a9-4730-a88a-69546f278494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;uclCust$uclCust$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;uclCust_uclCust_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>26230784-a06f-4951-9439-28e3a4b24716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
