<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEARCH_1_2</name>
   <tag></tag>
   <elementGuidId>c5091d18-16da-4c8b-b11b-ad759f03a1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a6b9ba3-5ca1-4b3b-8482-73fa2fc66c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>ae6739a7-6dd5-4914-8ae7-6cdbc4ea9e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>8b79e8f5-7b6f-4a8a-b256-6a86aa72b2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupTopUpAgrmnt$uclTopUpAgr$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>74a3e467-6393-4de7-b56a-0d1f37e25c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>e4c02829-2e2f-4a1e-b110-b90181bd1d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>bcf616c9-5982-4fe8-b707-cb728cc43101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get App No/iframe_Term  Condition_appForm</value>
      <webElementGuid>f381b736-8638-4a1f-8ed1-43c2051893ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>1991d2e1-48d7-4fe4-8856-bca09ddcd689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>38f788fc-8883-4b8d-af79-f6d298292dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[2]</value>
      <webElementGuid>5abb36dd-15ba-4eb9-922e-6fb9adf3a250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[3]/following::a[1]</value>
      <webElementGuid>46d3130d-0b0c-467f-b19c-e097c6a84238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract Status'])[1]/following::a[1]</value>
      <webElementGuid>dd3dc4cc-5383-4036-aca5-a4f79a2a2afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[2]/preceding::a[1]</value>
      <webElementGuid>7e861745-da68-421a-9cf3-ab2002eabcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[3]/preceding::a[2]</value>
      <webElementGuid>52b4a07c-a335-4ab8-bc5b-c8a38f6aaa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupTopUpAgrmnt$uclTopUpAgr$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>5100f2e5-d2b3-424d-9767-2161330a5a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td[2]/div/div/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>bf43f7d8-a02a-41fe-83eb-47f17f0f65d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucLookupTopUpAgrmnt$uclTopUpAgr$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucLookupTopUpAgrmnt_uclTopUpAgr_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>b5e298b8-c694-4a88-b07b-140ad1d0ee2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
