<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOSNEW APPLICATION</name>
   <tag></tag>
   <elementGuidId>cbce54e0-272d-4a6e-a879-3eba88dbe312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#linkPath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='linkPath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1d9d6ff-f67a-40eb-bd38-667accfd2173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkPath</value>
      <webElementGuid>8fec3332-4400-4cca-8899-33e54752ca98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    LOS/NEW APPLICATION
                </value>
      <webElementGuid>cdfe6947-4cab-4066-b756-a7dce4adb37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkPath&quot;)</value>
      <webElementGuid>3990778e-020f-4181-b322-3985e087396c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get App No/iframe_Welcome, ABDUL AZIS, TANGERANG, Mark_ad85bc</value>
      <webElementGuid>312e5add-36ff-4a39-84af-b6f874cee64f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='linkPath']</value>
      <webElementGuid>77da106e-63fb-4c83-8d89-18a7e1645172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upPath']/div</value>
      <webElementGuid>1b51c414-9c0e-4f21-8122-c676d1de83f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW APPLICATION'])[1]/preceding::div[1]</value>
      <webElementGuid>edd8751c-7865-418c-afdd-195b8d2c7d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>6651a2cd-f7c8-43c1-bec0-388ded54fa95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'linkPath' and (text() = '
                    LOS/NEW APPLICATION
                ' or . = '
                    LOS/NEW APPLICATION
                ')]</value>
      <webElementGuid>be5de210-63e6-4ee3-a380-9526ef628c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
