<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Copyright  AdIns 2011. All Right Rese_9109c2</name>
   <tag></tag>
   <elementGuidId>cd61fb57-4a7d-4712-ab63-dcb70ba4c3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06c80385-e006-4fe1-be8f-483687135ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>83ea6bda-7fb4-49c8-a6c2-551582b22e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>7a6f0613-eefb-4f5d-9b90-b6914d653052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>339f6b0d-f853-49b7-8b27-de5922d7c876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(!basicLoginValidation()) return false;</value>
      <webElementGuid>da8d381c-c399-4d20-b4cd-4576fbf08e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>658c45fc-23a8-42ac-b76c-8f2ddf452d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbLogin&quot;)</value>
      <webElementGuid>114964d3-9bff-4423-a6d5-56b846f7d266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbLogin']</value>
      <webElementGuid>f2befd15-cc41-4456-9413-2cfbed3e830f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upButton']/input</value>
      <webElementGuid>3bf0ecb4-1698-4f8b-a329-9ca306edcc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/input</value>
      <webElementGuid>560ef4da-b206-4fd0-aa27-0f467ec7ba89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lbLogin' and @id = 'lbLogin']</value>
      <webElementGuid>68d79553-485e-4ca4-b271-b4b52018f014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
