<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SD1SDRGK5150GJ703309_gvAssetListctl02imbEdit</name>
   <tag></tag>
   <elementGuidId>46f25e72-628e-4d46-8a9a-c4e75011197a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAssetList_imbEdit_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetList_imbEdit_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d222c72b-ab61-4f30-8dc9-4f3469f00d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c048f6b1-c722-43bd-a099-1c6559a15b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetList$ctl02$imbEdit</value>
      <webElementGuid>5c09ad97-babb-43a6-a509-15e0d17c823b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetList_imbEdit_0</value>
      <webElementGuid>b18d6ac3-8887-4efd-843a-7507466462f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Asset Registration</value>
      <webElementGuid>89d52c13-d4c0-436e-83bf-5721527ec068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Edit.gif</value>
      <webElementGuid>0436dfc5-9fa3-4973-aa13-61bf19fa05be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvAssetList_imbEdit_0&quot;)</value>
      <webElementGuid>504b2e9e-d4d9-44a2-88b8-be6516ef363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get App No/iframe_Term  Condition_appForm</value>
      <webElementGuid>dce4fcda-8479-4966-8491-720a22648dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetList_imbEdit_0']</value>
      <webElementGuid>5025775e-f05e-43e3-98b2-94087d045d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetList']/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>97bba976-f591-4f9c-b892-5f945487fa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>0b9ff3a8-60f1-4d4e-a3e1-11f937efbc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvAssetList$ctl02$imbEdit' and @id = 'gvAssetList_imbEdit_0' and @title = 'Asset Registration' and @src = '../../../../Images/Edit.gif']</value>
      <webElementGuid>75200d3c-43b4-4c0d-b66c-133597eb11e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
