<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-ext_ucAddrtxtPhoneExt1</name>
   <tag></tag>
   <elementGuidId>657c0395-cea8-49b9-8b56-10bfb48e6d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_txtPhoneExt1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_txtPhoneExt1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a6d41bf-b793-4552-b61b-b8d5e8937f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$txtPhoneExt1</value>
      <webElementGuid>a152b1cb-6788-4ed2-a0fe-384caca1a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d0b2575-fc29-48e9-96da-d416c3efac96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4bf4118f-c3a9-4656-81fc-63d89723239c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_txtPhoneExt1</value>
      <webElementGuid>f18e2ded-0ce9-48ca-a0ea-19b5abbbcf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtShortInputStyle</value>
      <webElementGuid>e35e6610-4599-4539-9f96-299b383ef752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_txtPhoneExt1&quot;)</value>
      <webElementGuid>0e883e25-c0de-465d-870a-26fd2ab37571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get App No/iframe_Term  Condition_appForm</value>
      <webElementGuid>a52762a1-698d-4ced-8aff-e232d0f85b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_txtPhoneExt1']</value>
      <webElementGuid>6da5033b-1515-4ac5-8fa4-c9e68b0c9c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ucAddr_trPhn1']/td[2]/input[3]</value>
      <webElementGuid>4476c6f0-b3f3-417e-8abd-664f8e0443d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input[3]</value>
      <webElementGuid>49ab4a0b-afd0-4f84-acb6-91c70437097b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAddr$txtPhoneExt1' and @type = 'text' and @id = 'ucAddr_txtPhoneExt1']</value>
      <webElementGuid>ce286694-f1e1-427c-9fab-cdf39dbcb24a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
