<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_company_officer2</name>
   <tag></tag>
   <elementGuidId>79d28418-6a27-4fd1-babf-730005b98aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[3]/div[2]/table/tbody/tr[3]/td[2]/ul/li[1]/input[2][count(. | //*[@ref_element = 'Object Repository/Document Signer/Document Signer Company/iframe_Welcome, ANGGO BAGUS WICAKSONO, TANG_7b644c']) = count(//*[@ref_element = 'Object Repository/Document Signer/Document Signer Company/iframe_Welcome, ANGGO BAGUS WICAKSONO, TANG_7b644c'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uclOfficeEmp2_uclOfficeEmp_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclOfficeEmp2_uclOfficeEmp_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclOfficeEmp2$uclOfficeEmp$imb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclOfficeEmp2_uclOfficeEmp_imb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Icon/IconLookup.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnuclOfficeEmp2_uclOfficeEmp');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[3]/div[2]/table/tbody/tr[3]/td[2]/ul/li[1]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Document Signer/Document Signer Company/iframe_Welcome, ANGGO BAGUS WICAKSONO, TANG_7b644c</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclOfficeEmp2_uclOfficeEmp_imb']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dCompanySigner']/table/tbody/tr[3]/td[2]/ul/li/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr[3]/td[2]/ul/li/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
