<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transfer_rtPlus</name>
   <tag></tag>
   <elementGuidId>67a6807c-77de-49d1-8ec7-aaee74a55281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[4]/div[2]/div/ul/li[5]/div/span[2][count(. | //*[@class = 'rtPlus' and @ref_element = 'Object Repository/Asset Document/Release/Release Approval/iframe_Welcome, SUGIHARTINI, TANGERANG, Ser_ffd6b9']) = count(//*[@class = 'rtPlus' and @ref_element = 'Object Repository/Asset Document/Release/Release Approval/iframe_Welcome, SUGIHARTINI, TANGERANG, Ser_ffd6b9'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rtvMenuTree']/ul/li[5]/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c37aa2c2-0585-4cf9-8e2e-70dfd46509c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtPlus</value>
      <webElementGuid>e323177b-41a2-461e-a852-f08299c8ebb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div[2]/div/ul/li[5]/div/span[2]</value>
      <webElementGuid>cdad4733-0e0a-4267-aba1-060985a199af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Asset Document/Release/Release Approval/iframe_Welcome, SUGIHARTINI, TANGERANG, Ser_ffd6b9</value>
      <webElementGuid>d0c6a7fe-33e4-4bd3-8acd-49c6c8332abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rtvMenuTree']/ul/li[5]/div/span[2]</value>
      <webElementGuid>0c32bcec-8a33-4887-8067-2f49c44e52a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/span[2]</value>
      <webElementGuid>cb575fe4-991b-4c97-b64e-b3bd69235306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
