<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_check_winner</name>
   <tag></tag>
   <elementGuidId>64416907-2201-44bd-a866-5a2f3cb2cddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div/div/div[4]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[4]/input[count(. | //*[@ref_element = 'Object Repository/COLLECTION/Inventory Selling/Inventory Selling Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1']) = count(//*[@ref_element = 'Object Repository/COLLECTION/Inventory Selling/Inventory Selling Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvListBidders_rbWinner_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvListBidders_rbWinner_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListBidders_rbWinner_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvListBidders$ctl02$rbWinner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rbWinner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:RadioChecked('gvListBidders_rbWinner_0');setTimeout('__doPostBack(\'gvListBidders$ctl02$rbWinner\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div/div/div[4]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[4]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Inventory Selling/Inventory Selling Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvListBidders_rbWinner_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvListBidders']/tbody/tr[2]/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
