<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-ext_UCAddresstxtPhn1</name>
   <tag></tag>
   <elementGuidId>58fcdb14-61f3-4e64-9fab-94244ea23e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UCAddress_txtPhn1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[4]/div/div/div[2]/div/div[3]/div/div/table/tbody/tr[8]/td[2]/input[2][count(. | //*[@ref_element = 'Object Repository/Corporate Customer/Address/iframe_Other Attribute_custForm']) = count(//*[@ref_element = 'Object Repository/Corporate Customer/Address/iframe_Other Attribute_custForm'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UCAddress_txtPhn1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UCAddress$txtPhn1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UCAddress_txtPhn1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedInputStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[4]/div/div/div[2]/div/div[3]/div/div/table/tbody/tr[8]/td[2]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Corporate Customer/Address/iframe_Other Attribute_custForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UCAddress_txtPhn1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='UCAddress_trPhn1']/td[2]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
