<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select_1</name>
   <tag></tag>
   <elementGuidId>45d5029e-cbc4-4f7a-b48f-30ddcf495ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCoyCommissioner_uclCustCoyShareHolder_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCoyCommissioner_uclCustCoyShareHolder_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[5]/a[count(. | //*[@ref_element = 'Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532']) = count(//*[@ref_element = 'Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCoyCommissioner_uclCustCoyShareHolder_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustCoyShareHolderLookup('uclCoyCommissioner_uclCustCoyShareHolder_txt','uclCoyCommissioner_uclCustCoyShareHolder_hd1','FATHONI ERLAMBANG','uclCoyCommissioner_uclCustCoyShareHolder_hd2','265519','uclCoyCommissioner_uclCustCoyShareHolder_hd3','246','uclCoyCommissioner_uclCustCoyShareHolder_hd4','176358','uclCoyCommissioner_uclCustCoyShareHolder_hd5','4502','uclCoyCommissioner_uclCustCoyShareHolder_hd6','AWANG LONG NO 41 009 000 BONTANG KUALA BONTANG UTARA BONTANG 75312','uclCoyCommissioner_uclCustCoyShareHolder_hd7','50.000000','uclCoyCommissioner_uclCustCoyShareHolder_hd8','DIREKTUR');;overlay('mdnuclCoyCommissioner_uclCustCoyShareHolder');__doPostBack('mdnuclCoyCommissioner_uclCustCoyShareHolder', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[5]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCoyCommissioner_uclCustCoyShareHolder_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCoyCommissioner_uclCustCoyShareHolder_umd_ctl00_gvL']/tbody/tr[2]/td[5]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIREKTUR'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWANG LONG NO 41 009 000 BONTANG KUALA BONTANG UTARA BONTANG 75312'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUHAYATI'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWANG LONG NO 41 009 000 BONTANG KUALA BONTANG UTARA BONTANG 75312'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustCoyShareHolderLookup('uclCoyCommissioner_uclCustCoyShareHolder_txt','uclCoyCommissioner_uclCustCoyShareHolder_hd1','FATHONI ERLAMBANG','uclCoyCommissioner_uclCustCoyShareHolder_hd2','265519','uclCoyCommissioner_uclCustCoyShareHolder_hd3','246','uclCoyCommissioner_uclCustCoyShareHolder_hd4','176358','uclCoyCommissioner_uclCustCoyShareHolder_hd5','4502','uclCoyCommissioner_uclCustCoyShareHolder_hd6','AWANG LONG NO 41 009 000 BONTANG KUALA BONTANG UTARA BONTANG 75312','uclCoyCommissioner_uclCustCoyShareHolder_hd7','50.000000','uclCoyCommissioner_uclCustCoyShareHolder_hd8','DIREKTUR');;overlay('mdnuclCoyCommissioner_uclCustCoyShareHolder');__doPostBack('mdnuclCoyCommissioner_uclCustCoyShareHolder', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
   </webElementXpaths>
</WebElementEntity>
