<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Commisioner Approver 1_uclCo_f26358</name>
   <tag></tag>
   <elementGuidId>c7a7a185-f936-4842-8658-1d19503ab4a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCoyApprover1_uclCustCoyShareHolder_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclCoyApprover1_uclCustCoyShareHolder_imb']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[5]/div[2]/table/tbody/tr[1]/td[2]/ul/li[1]/input[2][count(. | //*[@ref_element = 'Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532']) = count(//*[@ref_element = 'Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclCoyApprover1$uclCustCoyShareHolder$imb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCoyApprover1_uclCustCoyShareHolder_imb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Icon/IconLookup.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnuclCoyApprover1_uclCustCoyShareHolder');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[5]/div[2]/table/tbody/tr[1]/td[2]/ul/li[1]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FLEET/Document Signer/iframe_Welcome, HELEN MELIANA SETIAWAN, FLE_5ee532</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclCoyApprover1_uclCustCoyShareHolder_imb']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dApproverSigner']/table/tbody/tr/td[2]/ul/li/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/table/tbody/tr/td[2]/ul/li/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
