<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_repossess</name>
   <tag></tag>
   <elementGuidId>d0d4ac45-3f79-4820-9f26-c70f1362c465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvPaging_imbExtend_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[3]/div[3]/div[2]/div/div/div[2]/table/tbody/tr[2]/td[13]/input[count(. | //*[@ref_element = 'Object Repository/COLLECTION/Repossession Remedial Expense v3/iframe_Welcome, RULLY INDRA PERMANA, REMEDI_58e108']) = count(//*[@ref_element = 'Object Repository/COLLECTION/Repossession Remedial Expense v3/iframe_Welcome, RULLY INDRA PERMANA, REMEDI_58e108'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvPaging_imbExtend_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvPaging$ctl02$imbExtend</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvPaging_imbExtend_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Repossess</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Images/Edit.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div[3]/div[2]/div/div/div[2]/table/tbody/tr[2]/td[13]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Repossession Remedial Expense v3/iframe_Welcome, RULLY INDRA PERMANA, REMEDI_58e108</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvPaging_imbExtend_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvPaging']/tbody/tr[2]/td[13]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/input</value>
   </webElementXpaths>
</WebElementEntity>
