<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_waived_percentage</name>
   <tag></tag>
   <elementGuidId>788acb99-85ce-45fe-9aee-707dd5de7e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div/div/table/tbody/tr[2]/td[3]/input[2][count(. | //*[@ref_element = 'Object Repository/PAYMENT/Waived Transaction/Waived Request/iframe_Welcome, WANDA YUHANDA SARI, JAKARTA_f61394']) = count(//*[@ref_element = 'Object Repository/PAYMENT/Waived Transaction/Waived Request/iframe_Welcome, WANDA YUHANDA SARI, JAKARTA_f61394'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvPaymentAllocationDetail$ctl03$ucWaivedPrcntge$txtInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValuePercent('gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1','gvPaymentAllocationDetail_ucWaivedPrcntge_1_hdnInput_1','gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInputDummy_1');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div/div/table/tbody/tr[2]/td[3]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PAYMENT/Waived Transaction/Waived Request/iframe_Welcome, WANDA YUHANDA SARI, JAKARTA_f61394</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvPaymentAllocationDetail_ucWaivedPrcntge_1_txtInput_1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvPaymentAllocationDetail']/tbody/tr[3]/td[3]/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
