<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select (1)</name>
   <tag></tag>
   <elementGuidId>42e7b9e2-d649-45d5-93bf-8c12c0d52162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17d163f4-7053-4242-9ebe-3c3dd5b051ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6</value>
      <webElementGuid>97923912-4fee-48a2-843e-c205281b7e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','TAF SiapDana Platinum Commercial - Multiguna','ucLookupProdOffer_uclProductOffering_hd2','42325','ucLookupProdOffer_uclProductOffering_hd3','SBR21706');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')</value>
      <webElementGuid>497af02f-2191-442d-aea3-71b7ef5f0250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>edd7934d-ff0b-4acd-a301-c27fe4a8f80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6&quot;)</value>
      <webElementGuid>4e2c3bb4-5998-4a97-bc8a-84addaab9c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get NoSi NoKa/iframe_Welcome, ABDUL AZIS, TANGERANG, Mark_ad85bc</value>
      <webElementGuid>f5e56d7f-4395-41c3-a5e6-cc52e805e67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6']</value>
      <webElementGuid>94080981-eace-4d63-a58d-cf16c822f7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL']/tbody/tr[8]/td[3]/a</value>
      <webElementGuid>d25c5b2a-6b32-43a7-a8ad-190fa65182e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[7]</value>
      <webElementGuid>eed6a462-385a-4874-afac-a773e83b7120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBR21706'])[1]/following::a[1]</value>
      <webElementGuid>0ec7a07e-641b-4138-9017-13a38e112114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAF SiapDana Platinum Commercial - Multiguna'])[1]/following::a[1]</value>
      <webElementGuid>93fda349-953a-4907-935c-5d0ec11ae2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAF SiapDana Platinum Passenger - Multiguna'])[1]/preceding::a[1]</value>
      <webElementGuid>dca81a3c-1d21-4c0d-8773-a27c2b7ebf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBR21705'])[1]/preceding::a[1]</value>
      <webElementGuid>e3d43318-ca1a-441c-9904-aba28d04a476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','TAF SiapDana Platinum Commercial - Multiguna','ucLookupProdOffer_uclProductOffering_hd2','42325','ucLookupProdOffer_uclProductOffering_hd3','SBR21706');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')&quot;)]</value>
      <webElementGuid>c6746f7c-ff80-4754-94f7-6b447fc81bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/a</value>
      <webElementGuid>12188b19-ff47-4b0f-9814-457e08f66b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_6' and @href = concat(&quot;javascript:ProductOfferingLookup(&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TAF SiapDana Platinum Commercial - Multiguna&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;42325&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;SBR21706&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6b42e945-b8ee-4cdf-befd-4c4e8b210cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
