<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select (2)</name>
   <tag></tag>
   <elementGuidId>d4492f1f-e02c-417a-88fd-910d9e398819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8900b3b-13aa-4cf0-9b6e-408ec6d8aa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>309ad216-cb09-4b8b-92e3-e177d15e9c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','Zisimos Valavanis Seven','uclCust_uclCust_hd2','0037C20220501459','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','uclCust_uclCust_hd7','1732984','uclCust_uclCust_hd8','1732984');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
      <webElementGuid>6e087c6f-57e2-480d-93e4-4afbd77a4be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>bcbf70fd-b3e2-4fea-9af4-63c2f40dae68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>e7bf510b-c389-487a-a68e-232931d63b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get NoSi NoKa/iframe_Term  Condition_appForm</value>
      <webElementGuid>125af7f7-b29e-4650-aa42-95bb4910b7de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>3606b907-4fc7-4928-9ab6-476de9eb2af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>479a3229-6f96-4749-96f5-0100763aa7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>d24ce78d-b852-4225-b4b6-735d22d27d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan Gatot Subroto No. 123 Jakarta Selatan'])[1]/following::a[1]</value>
      <webElementGuid>f76054ff-8f4e-44d9-92c7-7301cf83437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>7ab1bdbd-7905-4a62-b14a-b7325f641daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>2292df4a-a29b-416d-8ee5-0a57cdc06abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>a856b3e4-230b-4ad0-b8f6-e3798750f302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','Zisimos Valavanis Seven','uclCust_uclCust_hd2','0037C20220501459','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','uclCust_uclCust_hd7','1732984','uclCust_uclCust_hd8','1732984');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
      <webElementGuid>d1b43dbf-f662-4232-af26-eda8c86cbffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>825ad53d-0972-47b5-bdb5-64966b0a79f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CustLookup(&quot; , &quot;'&quot; , &quot;uclCust_uclCust_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Zisimos Valavanis Seven&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;0037C20220501459&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;P&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Personal&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Jalan Gatot Subroto No. 123 Jakarta Selatan&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1732984&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1732984&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>70991430-8aef-478c-8f22-b6121495b80e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
