<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome, ABDUL AZIS, TANGERANG, Marketi_f0727e</name>
   <tag></tag>
   <elementGuidId>6127ddf5-cf08-480d-8791-255323245b0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d579959-e641-4476-83d7-2ad39307bd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgMenu</value>
      <webElementGuid>1add1263-467f-4160-9cbb-c35b2a4542f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/menu.png</value>
      <webElementGuid>f5891a78-ce3e-4abc-9b15-1b5ac87108b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgMenu&quot;)</value>
      <webElementGuid>5474a007-ede1-421b-a4f8-4e0eaed4733d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgMenu']</value>
      <webElementGuid>7f3f867f-09b6-44a7-9f8f-493663482ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuPadding']/img</value>
      <webElementGuid>a1a7451d-4916-4cb8-8dfd-8fa2026302bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>1c79c169-8f4c-4c89-a6bd-bc67e3ed6f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgMenu' and @src = 'Images/menu.png']</value>
      <webElementGuid>2ef2157d-84da-4cf3-9502-a2976c5ee633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
