<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_lb_Form_SaveCont</name>
   <tag></tag>
   <elementGuidId>ce860428-4a3c-43d7-8dcb-278690ed00fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_SaveCont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_SaveCont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e2f6b26-97e4-4d4e-a8d2-524152efe013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>15aa1504-e8c7-4fd2-9b66-c44ee2231e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>22f1ce04-f569-440e-9d82-4de4b9ecab09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Continue</value>
      <webElementGuid>1c40276a-2775-476c-a533-73be65f273d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_SaveCont&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>0fb45b5a-28c1-4fff-bb86-20ca7ccaa375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>8e6d48f6-8ee4-44c1-94ca-e406a6092e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>b953d5a7-7907-4c02-9c2a-c2cdf949a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Form_SaveCont&quot;)</value>
      <webElementGuid>5e32c73c-d366-49f9-aa19-ac49cc1ebf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIAP DANA/Siap Dana Matching/Get NoSi NoKa/iframe_Term  Condition_appForm</value>
      <webElementGuid>fbbd2fe9-ab9d-4f58-b160-20c0bc1a080e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_SaveCont']</value>
      <webElementGuid>e8938a7c-8ae0-45c8-9bfa-2b37f59dada4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upBtn']/table/tbody/tr/td/div/input</value>
      <webElementGuid>d060bed1-d71f-4660-b0ab-a9ee7410f39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c9161b33-928a-4cb1-b867-8cef134e059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_Form_SaveCont' and @id = 'lb_Form_SaveCont']</value>
      <webElementGuid>ff25e92d-eab6-4138-8b4c-4e7e5b618008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
