<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Establishment Date_ucDPEstablishmentD_d0d9ee</name>
   <tag></tag>
   <elementGuidId>42456fea-10ec-4d52-ba7a-798d2a19483f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucDPEstablishmentDate_txtDatePicker</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[3]/div/div[3]/table/tbody/tr[3]/td[2]/input[1][count(. | //*[@ref_element = 'Object Repository/Corporate Customer/New - Main Data/iframe_Other Attribute_custForm']) = count(//*[@ref_element = 'Object Repository/Corporate Customer/New - Main Data/iframe_Other Attribute_custForm'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucDPEstablishmentDate_txtDatePicker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucDPEstablishmentDate$txtDatePicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucDPEstablishmentDate_txtDatePicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucDPEstablishmentDate_txtDatePicker','ucDPEstablishmentDate_txtHidden', 'ucDPEstablishmentDate_rvDate')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div/div[3]/table/tbody/tr[3]/td[2]/input[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Corporate Customer/New - Main Data/iframe_Other Attribute_custForm</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucDPEstablishmentDate_txtDatePicker']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainData']/table/tbody/tr[3]/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
