<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search_deduction_item</name>
   <tag></tag>
   <elementGuidId>635eb616-34d7-4159-b84b-9fa5b7bd1f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div/div/div[6]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[1]/div/div/div/div/div[1]/table/tbody/tr/td/div/a[1][count(. | //*[@ref_element = 'Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1']) = count(//*[@ref_element = 'Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvListDeduction$ctl02$ucLookupDeduction$uclDeduction$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0VldtnGrp&quot;, &quot;&quot;, false, true))</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div/div/div[6]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[1]/div/div/div/div/div[1]/table/tbody/tr/td/div/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_upButtonSearch_0']/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'SEARCH')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dedution Item'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOOK UP - Deduction Lookup'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[8]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvListDeduction$ctl02$ucLookupDeduction$uclDeduction$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;gvListDeduction_ucLookupDeduction_0_uclDeduction_0_umd_0_ctl00_0_ucS_0_lbSearch_0VldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/div/div/div/table/tbody/tr/td/div/a</value>
   </webElementXpaths>
</WebElementEntity>
