<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_search_deduction</name>
   <tag></tag>
   <elementGuidId>93a3cdea-4590-4a3f-83f5-6a7ae8cad9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvListDeduction_ucLookupDeduction_0_uclDeduction_0_imb_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div/div/div[6]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[1]/ul/li[1]/input[2][count(. | //*[@ref_element = 'Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1']) = count(//*[@ref_element = 'Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvListDeduction_ucLookupDeduction_0_uclDeduction_0_imb_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvListDeduction$ctl02$ucLookupDeduction$uclDeduction$imb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvListDeduction_ucLookupDeduction_0_uclDeduction_0_imb_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Icon/IconLookup.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdngvListDeduction_ucLookupDeduction_0_uclDeduction_0');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div/div/div[6]/div/div/div[2]/div[2]/table/tbody/tr[2]/td[1]/ul/li[1]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/REMEDIAL/Asset Appraisal/Asset Appraisal Request/iframe_Welcome, BACHTERA ESPANALDY, JAKARTA_f53dc1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvListDeduction_ucLookupDeduction_0_uclDeduction_0_imb_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvListDeduction']/tbody/tr[2]/td/ul/li/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/ul/li/input[2]</value>
   </webElementXpaths>
</WebElementEntity>
