<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_fc_ktp_an_bpkb</name>
   <tag></tag>
   <elementGuidId>c2acb921-d82e-4371-9965-456943a60c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAssetDoc_cbChecked_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvAssetDoc_cbChecked_5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div/div[10]/div/div/table/tbody/tr[7]/td[5]/input[count(. | //*[@id = 'gvAssetDoc_cbChecked_5' and @ref_element = 'Object Repository/Delivery Order/Multi Asset/iframe_Welcome, AMAN ASTARI, TANGERANG, Sal_748683']) = count(//*[@id = 'gvAssetDoc_cbChecked_5' and @ref_element = 'Object Repository/Delivery Order/Multi Asset/iframe_Welcome, AMAN ASTARI, TANGERANG, Sal_748683'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAssetDoc_cbChecked_5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAssetDoc$ctl07$cbChecked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvAssetDoc$ctl07$cbChecked\',\'\')', 0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div/div[10]/div/div/table/tbody/tr[7]/td[5]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Delivery Order/Multi Asset/iframe_Welcome, AMAN ASTARI, TANGERANG, Sal_748683</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAssetDoc_cbChecked_5']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAssetDoc']/tbody/tr[7]/td[5]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]/input</value>
   </webElementXpaths>
</WebElementEntity>
