<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_select_customer2</name>
   <tag></tag>
   <elementGuidId>4f03e155-dd13-48c1-bdab-cfe50f5f9463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucCustMainDataPersonal_ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucCustMainDataPersonal_ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCustMainDataPersonal_ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('ucCustMainDataPersonal_ucLookupCust_uclCust_txt','ucCustMainDataPersonal_ucLookupCust_uclCust_hd1','Teresita Rodarte Two','ucCustMainDataPersonal_ucLookupCust_uclCust_hd2','0037C20211205695','ucCustMainDataPersonal_ucLookupCust_uclCust_hd3','P','ucCustMainDataPersonal_ucLookupCust_uclCust_hd4','Personal','ucCustMainDataPersonal_ucLookupCust_uclCust_hd5','-','ucCustMainDataPersonal_ucLookupCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','ucCustMainDataPersonal_ucLookupCust_uclCust_hd7','1661685','ucCustMainDataPersonal_ucLookupCust_uclCust_hd8','1661685');;overlay('mdnucCustMainDataPersonal_ucLookupCust_uclCust');__doPostBack('mdnucCustMainDataPersonal_ucLookupCust_uclCust', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[8]/div/div[2]/div/table/tbody/tr[1]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[6]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EKYC/Application/CDE Completion Company/iframe_Welcome, TITO ARI PRABOWO, AREA 2, C_85b3dc</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucCustMainDataPersonal_ucLookupCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucCustMainDataPersonal_ucLookupCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jalan Gatot Subroto No. 123 Jakarta Selatan'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('ucCustMainDataPersonal_ucLookupCust_uclCust_txt','ucCustMainDataPersonal_ucLookupCust_uclCust_hd1','Teresita Rodarte Two','ucCustMainDataPersonal_ucLookupCust_uclCust_hd2','0037C20211205695','ucCustMainDataPersonal_ucLookupCust_uclCust_hd3','P','ucCustMainDataPersonal_ucLookupCust_uclCust_hd4','Personal','ucCustMainDataPersonal_ucLookupCust_uclCust_hd5','-','ucCustMainDataPersonal_ucLookupCust_uclCust_hd6','Jalan Gatot Subroto No. 123 Jakarta Selatan','ucCustMainDataPersonal_ucLookupCust_uclCust_hd7','1661685','ucCustMainDataPersonal_ucLookupCust_uclCust_hd8','1661685');;overlay('mdnucCustMainDataPersonal_ucLookupCust_uclCust');__doPostBack('mdnucCustMainDataPersonal_ucLookupCust_uclCust', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
