<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_select_zipCode</name>
   <tag></tag>
   <elementGuidId>0aeef0fd-9330-40b5-a497-b3ac45221868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucAddress_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucAddress_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddress_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ZipCode('ucAddress_ucLookupZipCode_uclZipCode_txt','ucAddress_ucLookupZipCode_uclZipCode_hd1','12780','ucAddress_ucLookupZipCode_uclZipCode_hd2','PANCORAN','ucAddress_ucLookupZipCode_uclZipCode_hd3','PANCORAN','ucAddress_ucLookupZipCode_uclZipCode_hd4','JAKARTA SELATAN','ucAddress_ucLookupZipCode_uclZipCode_hd5','-','ucAddress_ucLookupZipCode_uclZipCode_hd6','Wil. Kota Jakarta Selatan','ucAddress_ucLookupZipCode_uclZipCode_hd7','161');;overlay('mdnucAddress_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddress_ucLookupZipCode_uclZipCode', '')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[6]/div/div[2]/div[2]/div/table/tbody/tr[3]/td[2]/div/div/div/div/div[2]/div/div[1]/table/tbody/tr[2]/td[7]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/EKYC/Application/CDE Completion Company/iframe_Welcome, TITO ARI PRABOWO, AREA 2, C_85b3dc</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucAddress_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucAddress_ucLookupZipCode_uclZipCode_umd_ctl00_gvL']/tbody/tr[2]/td[7]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wil. Kota Jakarta Selatan'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANCORAN MAS'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANCORAN MAS'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ZipCode('ucAddress_ucLookupZipCode_uclZipCode_txt','ucAddress_ucLookupZipCode_uclZipCode_hd1','12780','ucAddress_ucLookupZipCode_uclZipCode_hd2','PANCORAN','ucAddress_ucLookupZipCode_uclZipCode_hd3','PANCORAN','ucAddress_ucLookupZipCode_uclZipCode_hd4','JAKARTA SELATAN','ucAddress_ucLookupZipCode_uclZipCode_hd5','-','ucAddress_ucLookupZipCode_uclZipCode_hd6','Wil. Kota Jakarta Selatan','ucAddress_ucLookupZipCode_uclZipCode_hd7','161');;overlay('mdnucAddress_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddress_ucLookupZipCode_uclZipCode', '')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
   </webElementXpaths>
</WebElementEntity>
