<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_req_survey</name>
   <tag></tag>
   <elementGuidId>f6511329-ebaf-4d8d-8c81-8a7f8481e18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_ReqSurvey_Cust</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_ReqSurvey_Cust']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f3511a5-f1d4-4fc7-818b-11e0a99fd6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9de51e41-6c1d-428f-9e35-275f9a74c664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_ReqSurvey_Cust</value>
      <webElementGuid>924cddf5-f61b-453d-93a4-3ffa911006ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Request Survey</value>
      <webElementGuid>b51a2b19-7d74-4d7b-8e6f-d409a61632a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_ReqSurvey_Cust</value>
      <webElementGuid>72ba603f-96ff-4595-a8ee-fe221559b6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>74233684-bb85-4ced-bce4-3a9af836f209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div/table/tbody/tr[1]/td[4]/input</value>
      <webElementGuid>12d093fd-9265-49ae-bb15-3231d5bb7427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf req/iframe_Welcome, SUGIHARTINI, TANGERANG, CUS_b08983</value>
      <webElementGuid>9b195d43-4209-45be-b9a8-b9249a04448d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_ReqSurvey_Cust']</value>
      <webElementGuid>babe557f-a781-4bf9-942a-03f702aa539f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upAgrmntTrfReq']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>55f873db-55d6-4dfa-ae76-8057920511aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>6a6e9354-3a6f-4526-bb25-40251870d129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_Form_ReqSurvey_Cust' and @id = 'lb_Form_ReqSurvey_Cust']</value>
      <webElementGuid>8ba537f2-a866-4e70-8a53-ced57a7a9d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
