<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_fc_ktp_penjamin</name>
   <tag></tag>
   <elementGuidId>9baec644-abed-4ea7-b8b4-e141594d86a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>695e204b-b1cc-4801-ba6e-6341d1229b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_3</value>
      <webElementGuid>148b3aae-e83e-45bc-b129-f1070df7dfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c002ae9d-58f6-4961-9f08-ee8536c44804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl05$cbChecked</value>
      <webElementGuid>0c97791f-f489-4fd2-880c-aa6f7fe94602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl05$cbChecked\',\'\')', 0)</value>
      <webElementGuid>29555aed-7dea-4753-ab3c-8d47a793ceed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[8]/div[2]/div/table/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>a110b0a9-3604-41de-ac09-1cec29ee581e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf req/iframe_Welcome, SUGIHARTINI, TANGERANG, CUS_b08983</value>
      <webElementGuid>720cb44c-28f5-4805-b59b-bc1b4d3dd767</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_3']</value>
      <webElementGuid>f45c021e-3f6b-4100-a739-f9e8d738bda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>7ebba042-1312-4948-b5f4-c940be1b7b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>ffc8b7c2-b48a-4ff5-9ee6-45c4d830cd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_3' and @type = 'checkbox' and @name = 'gvTermCondition$ctl05$cbChecked']</value>
      <webElementGuid>14db28e0-6c0e-4192-ba81-bcc4fe52e835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
