<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_fc_paspor</name>
   <tag></tag>
   <elementGuidId>477ec377-1def-49da-944b-2293824bc715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11d4136b-e475-44f5-96f2-ee069edb72c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_4</value>
      <webElementGuid>072bd429-2f6c-46b9-96ee-ba04fab5b9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73e7d0f9-19b3-4f8d-9575-a81882c313c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl06$cbChecked</value>
      <webElementGuid>85f5cf7a-adab-4a24-a646-0a2fe2784d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl06$cbChecked\',\'\')', 0)</value>
      <webElementGuid>38de22a0-3b56-4ef3-b3fb-39016f718428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[8]/div[2]/div/table/tbody/tr[6]/td[4]/input</value>
      <webElementGuid>61384781-d7c0-4945-a55c-c1580776fcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf req/iframe_Welcome, SUGIHARTINI, TANGERANG, CUS_b08983</value>
      <webElementGuid>0da38a41-a263-475a-8fda-90b24876b57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_4']</value>
      <webElementGuid>21010eb5-0f78-4db4-b02d-9364fd7dc0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[6]/td[4]/input</value>
      <webElementGuid>3f483ec5-3c77-465d-bc96-c1bf3a79a500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/input</value>
      <webElementGuid>9dacd083-78cc-4905-b65b-ee75cfab7ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_4' and @type = 'checkbox' and @name = 'gvTermCondition$ctl06$cbChecked']</value>
      <webElementGuid>8cc270a4-7e75-452f-902f-86c7300bc4b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
