<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_fc_kk</name>
   <tag></tag>
   <elementGuidId>7d63b75c-fb84-45e0-8c9e-093f823e18ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvTermCondition_cbChecked_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvTermCondition_cbChecked_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de5ffcec-a291-40d0-be25-569fac350ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvTermCondition_cbChecked_5</value>
      <webElementGuid>0c96a77e-2a85-4f3b-9a46-73494dc86f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>445dc855-7492-49e4-b135-f940b4db93e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvTermCondition$ctl07$cbChecked</value>
      <webElementGuid>0acf1267-da79-4acf-85ed-2d2a406f4de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'gvTermCondition$ctl07$cbChecked\',\'\')', 0)</value>
      <webElementGuid>f9280e64-c037-491b-914d-0fef4cc107ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[8]/div[2]/div/table/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>af57bf9b-17f7-42b3-9a07-33b5800c0813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf req/iframe_Welcome, SUGIHARTINI, TANGERANG, CUS_b08983</value>
      <webElementGuid>0741af72-8ecf-4438-9894-d7c562020dcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvTermCondition_cbChecked_5']</value>
      <webElementGuid>e64005a8-dd03-4a02-b449-fca1c9a73a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvTermCondition']/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>550aafff-5399-4061-9e3e-e7ef4511dee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/input</value>
      <webElementGuid>9a52c130-ce42-4f00-877e-e20304a57c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gvTermCondition_cbChecked_5' and @type = 'checkbox' and @name = 'gvTermCondition$ctl07$cbChecked']</value>
      <webElementGuid>d5b76d5e-82e7-415b-8d13-c3a2be2a2aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
