<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_notes_analysis</name>
   <tag></tag>
   <elementGuidId>c5d4c7db-b511-4476-af4e-19371fdb4289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAnalysis_txtAnalysisNotes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[5]/div/div/div/div[2]/table/tbody/tr[4]/td[2]/textarea[count(. | //*[@ref_element = 'Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434']) = count(//*[@ref_element = 'Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ucAnalysis_txtAnalysisNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAnalysis$txtAnalysisNotes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAnalysis_txtAnalysisNotes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[5]/div/div/div/div[2]/table/tbody/tr[4]/td[2]/textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ucAnalysis_txtAnalysisNotes']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAnalysis']/table/tbody/tr[4]/td[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
