<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_account_name</name>
   <tag></tag>
   <elementGuidId>27b703dc-ff68-40bf-aa97-25f45a926a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAccName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[3]/div[8]/div[2]/table/tbody/tr[3]/td[4]/input[count(. | //*[@ref_element = 'Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434']) = count(//*[@ref_element = 'Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAccName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAccName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAccName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[3]/div[8]/div[2]/table/tbody/tr[3]/td[4]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/COLLECTION/Collection Expense v3/Collection Expense Request v3/iframe_Welcome, AJI KURNIAWAN, Jakarta Cent_091434</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAccName']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dBankAcc']/table/tbody/tr[3]/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
