<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_calculate</name>
   <tag></tag>
   <elementGuidId>1c969cd1-a03a-4c3f-a3d1-91bd6a24b760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_CalcInstRatio</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/form/div[5]/div[5]/div[5]/div/div[2]/table/tbody/tr[5]/td[2]/input[count(. | //*[@type = 'submit' and @name = 'lb_Form_CalcInstRatio' and @id = 'lb_Form_CalcInstRatio' and @ref_element = 'Object Repository/Credit Approval/CA Analyst Siap Dana/iframe_Welcome, NINA LARASATI, TANGERANG, C_783fec']) = count(//*[@type = 'submit' and @name = 'lb_Form_CalcInstRatio' and @id = 'lb_Form_CalcInstRatio' and @ref_element = 'Object Repository/Credit Approval/CA Analyst Siap Dana/iframe_Welcome, NINA LARASATI, TANGERANG, C_783fec'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_CalcInstRatio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_CalcInstRatio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_CalcInstRatio&quot;, &quot;&quot;, true, &quot;Income&quot;, &quot;&quot;, false, false))</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_CalcInstRatio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[5]/div[5]/div[5]/div/div[2]/table/tbody/tr[5]/td[2]/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Credit Approval/CA Analyst Siap Dana/iframe_Welcome, NINA LARASATI, TANGERANG, C_783fec</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_CalcInstRatio']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dIncome']/table/tbody/tr[5]/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
