<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_execute</name>
   <tag></tag>
   <elementGuidId>06864987-5a77-453f-9238-f9aeff158e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvAgrmnt_imbEdit_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvAgrmnt_imbEdit_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40f8ef66-ef2d-4299-8ad8-f8b363095abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>77b7a292-d98f-4aea-b95f-caaac003ca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvAgrmnt$ctl02$imbEdit</value>
      <webElementGuid>7d9cc8af-5e8f-4a25-a2dc-a80b82281091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvAgrmnt_imbEdit_0</value>
      <webElementGuid>cbaba7f2-8b7d-4c95-aff4-33c86a3c96b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Execute Record</value>
      <webElementGuid>81871e38-13d2-4e2e-a7c5-175181a10b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/Edit.gif</value>
      <webElementGuid>9f96ed52-d51d-4e58-a168-0f40acd3438b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvAgrmnt$ctl02$imbEdit&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>d0cc35f8-16bd-40a8-8367-aa1d9c24723d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/div[3]/div[2]/div/div[2]/div[2]/table/tbody/tr[2]/td[10]/input</value>
      <webElementGuid>ab7ae164-b679-41c2-a882-93a78e68e862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Overcredit/Amendment agr trf execution/iframe_Welcome, SUGIHARTINI, TANGERANG, CUS_b08983</value>
      <webElementGuid>dfa25e96-614f-49b0-8b70-d20c77943196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvAgrmnt_imbEdit_0']</value>
      <webElementGuid>3d3cf62d-5c97-4387-af38-05cd774eaebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvAgrmnt']/tbody/tr[2]/td[10]/input</value>
      <webElementGuid>fd5dc97c-d2af-43b2-8baa-ac70a12810ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>e93f0fb6-8c48-499f-aa3a-269c075f2225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvAgrmnt$ctl02$imbEdit' and @id = 'gvAgrmnt_imbEdit_0' and @title = 'Execute Record' and @src = '../Images/Edit.gif']</value>
      <webElementGuid>5f33cb9d-adb6-4292-a414-c61ea1f22bdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
